# Generated by Django 3.2.4 on 2021-06-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='img/carousel')),
                ('submittedat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='img/carousel')),
                ('submittedat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='img/carousel')),
                ('submittedat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=200, null=True)),
                ('gif', models.ImageField(null=True, upload_to='img/section')),
                ('submittedat', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
