# Generated by Django 3.2.4 on 2021-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
