# Generated by Django 3.2.4 on 2021-06-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0002_auto_20210622_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='content1',
        ),
        migrations.AddField(
            model_name='about',
            name='content2',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content3',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
