# Generated by Django 3.2.4 on 2021-06-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0003_auto_20210622_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='content2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='content3',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
