# Generated by Django 3.2.4 on 2021-06-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0004_auto_20210623_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='clients',
            name='img2',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
        migrations.AddField(
            model_name='clients',
            name='img3',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
        migrations.AddField(
            model_name='clients',
            name='img4',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
        migrations.AddField(
            model_name='clients',
            name='img5',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
        migrations.AddField(
            model_name='clients',
            name='img6',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
        migrations.AddField(
            model_name='clients',
            name='img7',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
        migrations.AddField(
            model_name='clients',
            name='img8',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
    ]
