# Generated by Django 3.2.4 on 2021-06-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0005_auto_20210623_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='Title',
            new_name='Title_1',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='content',
            new_name='content_1',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='gif',
            new_name='gif_1',
        ),
        migrations.AddField(
            model_name='section',
            name='Title_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Title_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Title_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Title_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='Title_6',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='content_2',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='content_3',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='content_4',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='content_5',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='content_6',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='gif_2',
            field=models.ImageField(null=True, upload_to='img/section'),
        ),
        migrations.AddField(
            model_name='section',
            name='gif_3',
            field=models.ImageField(null=True, upload_to='img/section'),
        ),
        migrations.AddField(
            model_name='section',
            name='gif_4',
            field=models.ImageField(null=True, upload_to='img/section'),
        ),
        migrations.AddField(
            model_name='section',
            name='gif_5',
            field=models.ImageField(null=True, upload_to='img/section'),
        ),
        migrations.AddField(
            model_name='section',
            name='gif_6',
            field=models.ImageField(null=True, upload_to='img/section'),
        ),
        migrations.AddField(
            model_name='section',
            name='heading',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
