# Generated by Django 3.2.4 on 2021-06-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0006_auto_20210623_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='description',
            new_name='description_1',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='heading',
            new_name='heading_1',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='img',
            new_name='img_1',
        ),
        migrations.AddField(
            model_name='carousel',
            name='description_2',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='description_3',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='heading_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='heading_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='img_2',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='img_3',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
    ]
