# Generated by Django 3.2.4 on 2021-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0007_auto_20210623_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='description_4',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='heading_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='img_4',
            field=models.ImageField(null=True, upload_to='img/carousel'),
        ),
    ]
