# Generated by Django 3.2.4 on 2021-06-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0008_auto_20210623_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='description_1',
            new_name='Description_1',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='description_2',
            new_name='Description_2',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='description_3',
            new_name='Description_3',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='description_4',
            new_name='Description_4',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='heading_1',
            new_name='Heading_1',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='heading_2',
            new_name='Heading_2',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='heading_3',
            new_name='Heading_3',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='heading_4',
            new_name='Heading_4',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='img_1',
            new_name='Img_1',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='img_2',
            new_name='Img_2',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='img_3',
            new_name='Img_3',
        ),
        migrations.RenameField(
            model_name='carousel',
            old_name='img_4',
            new_name='Img_4',
        ),
    ]
