# Generated by Django 3.2.4 on 2021-06-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodhitech', '0010_auto_20210624_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='content1',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='about',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='content3',
        ),
    ]
